### ISSUE TITLE
feat: add todo list 

### ISSUE THREAD

**Issue by daniqss** [daniqss/pomodoro#2]

**Comment by daniqss** [comment]
closed because im retarded

**Comment by daniqss** [comment]
- [x] add todos types and schemas
- [x] make it work
- [ ] drag and drop todos between users in room
